### ISSUE TITLE
git signing

### ISSUE THREAD

**Issue by juev** [cloudhead/dotfiles#3]
Hi,

As I can see, you trying to use ssh instead of  gpg ([commit](https://github.com/cloudhead/dotfiles/commit/4a9ce2f25624c12334db1a034c1531932d4f3459)).

But as I can see, this key is not exist on github:
<img width="373" alt="Снимок экрана 2021-11-28 в 09 25 10" src="https://user-images.githubusercontent.com/114635/143732068-b0e3af82-1aee-4e93-aa68-065dc0c3a22e.png">

Will this problem be solved?

**Comment by MrIsaacs** [comment]
I have also witnessed [that](https://github.com/cloudhead/dotfiles/blob/4a9ce2f25624c12334db1a034c1531932d4f3459/.gitconfig#L4) mishap and want to make sure you are aware of it.
This might help. 👇 
## [Encrypted secrets - GitHub Docs][1]
[**Encrypted secrets allow you to store sensitive information in your organization, repository, or repository environments.**
![image](https://user-images.githubusercontent.com/203188/181742177-8d8811c4-8ce2-4c6e-8b93-68b8e61fa66a.png)][1]

[1]: https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by cloudhead** [comment]
This is now implemented in GitHub :+1:
